// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuiAnhDung156.Migrations
{
    [DbContext(typeof(BUIANHDUNG156))]
    partial class BUIANHDUNG156ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuiAnhDung156.Models.BAD0156", b =>
                {
                    b.Property<string>("NVNId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("NVNGender")
                        .HasColumnType("bit");

                    b.Property<string>("NVNName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NVNId");

                    b.ToTable("BAD0156");
                });

            modelBuilder.Entity("BuiAnhDung156.Models.PersonBAD156", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonId");

                    b.ToTable("PersonBAD156");
                });
#pragma warning restore 612, 618
        }
    }
}
